/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 issLogo.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/issLogo-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['default']} position={[13.06, -20.72, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['default']} position={[6.33, -20.72, 0]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['default']} position={[-4.06, 8.25, 0]} scale={[0.44, 0.44, 1]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['default']} position={[12.62, -26.68, 0]} scale={[0.44, 0.44, 1]} />
    </group>
  )
}

useGLTF.preload('/issLogo-transformed.glb')
